### PR TITLE
added starter code

### PR DESCRIPTION
**Pull request by chetanya-shrimali**
django starter code added to submify

### CODE REVIEW

**Comment by yashLadha** [comment]
Remove .idea as they are not necessary to code.

**Comment by yashLadha** [comment]
If needed update the .gitignore as well

**Comment by TarunISCO** [comment]
@yashLadha please have a review.

**Comment by TarunISCO** [comment]
i think it is ready to be merged.

**Comment by chetanya-shrimali** [comment]
i do think so!!

**Comment by yashLadha** [comment]
@TarunISCO :+1:

**Pull request merged**
